---

- name: ensure VirtualBox dependencies are installed
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - binutils
    - gcc
    - make
    - patch
    - libgomp
    - glibc-headers
    - glibc-devel
    - kernel-headers
    - kernel-devel 
    - dkms

- name: ensure virtualbox is installed
  dnf:
    name: "{{ item }}"
    state: latest
  with_items:
    - VirtualBox
    - akmod-VirtualBox
  
